apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_call:
    inputs:
      artifact-id:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        with:
          repository: cb-golden-demo-org/harckers-organized-appro-web
      - uses: cloudbees-days/setup-kubeconfig
        name: Set kubeconfig
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/chart
          release-name: harckers-organized-appro-web
          namespace: ${{ vars.namespace }}
          values: |
            image:
              repository: ${{ vars.DOCKER_USER }}/harckers-organized-appro-web
              tag: ${{ inputs.artifactVersion }}
            hostname: harckers-organized-appro-web.${{ inputs.environment }}.preview.cb-demos.io
            config:
              fmKey: ${{ vars.FM_TOKEN }}
              apiUrl: https://harckers-organized-appro-api.${{ inputs.environment }}.preview.cb-demos.io/api
              authUrl: https://harckers-organized-appro-auth.${{ inputs.environment }}.preview.cb-demos.io
              useVPC: false
              fmInstance: cloudbees.io
      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.artifact-id }}
          target-environment: ${{ inputs.environment }}
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Deployed environment
            [Dev frontend](https://harckers-organized-appro-web.${{ inputs.environment }}.preview.cb-demos.io/)

            Running harckers-organized-appro-web:${{ inputs.artifactVersion }}
          format: MARKDOWN
